### ISSUE TITLE
Do we still need to include extra .stylx files for MSE at Pro 2.0

### ISSUE THREAD

**Issue by dfoll** [lfunkhouser/mta-progress#1]
check to see if the additional .stylx files are still needed for MSE with Pro 2.0, update (remove that section) if they are not needed

**Comment by dfoll** [comment]
C:\Program Files\ArcGIS\Pro\Resources\Dictionaries

**Comment by dfoll** [comment]
the answer is no, i will make the appropriate changes to do (removing those topics from the maps)

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/military-symbol-editor-addin-wpf#190
